org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod Info
mod_version=1.0.2
mod_name=Twilit Gourmet
modid=twilitgourmet

# Mappings
neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

# Versioning
minecraft_version=1.21.1
neo_version=21.1.248
jei_version=19.27.0.336
emi_version=1.1.22
tf_version=4.8.3345